# Generated by Django 3.2.5 on 2021-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0003_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9),
        ),
    ]
