# Generated by Django 3.2.5 on 2021-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0006_auto_20211223_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
    ]
