# Generated by Django 3.2.5 on 2021-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0009_auto_20211229_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
