# Generated by Django 3.2.5 on 2021-12-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0011_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=22),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='wholeCost',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
