# Generated by Django 3.2.5 on 2021-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0012_auto_20211229_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
        ),
    ]
